[package]
name = "baas-tauri"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant, but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "baas_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
baas-updater = { workspace = true }
baas-term = { workspace = true }
tauri = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }

tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
directories = "6.0.0"
tauri-plugin-process = "2"
tauri-plugin-updater = "2.10.1"
tauri-plugin-single-instance = "2"

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Win32_UI_HiDpi",
  "Win32_UI_WindowsAndMessaging",
] }
