[workspace]
members = [
  "src-tauri",
  "crates/baas-ipc",
  "crates/baas-updater",
  "crates/baas-term",
  "crates/baas-i18n",
  "crates/baas-shortcut",
  "crates/baas-notifier"
]
resolver = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = "symbols"

[workspace.dependencies]
baas-updater = { path = "crates/baas-updater" }
baas-ipc = { path = "crates/baas-ipc" }
baas-term = { path = "crates/baas-term" }
baas-i18n = { path = "crates/baas-i18n" }
baas-shortcut = { path = "crates/baas-shortcut" }
baas-notifier = { path = "crates/baas-notifier" }

tauri = { version = "2.11.2", features = ["devtools", "tray-icon"] }
tauri-plugin-notification = "2.3.3"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
chrono = { version = "0.4", features = ["clock", "serde"] }
tempfile = { version = "3" }
portable-pty = { version = "0.9.0" }
uuid = { version = "1", features = ["v4", "serde"] }
