[package]
name = "baas-updater"
version = "0.0.3"
edition = "2024"
readme = "README.md"
description = "Package used for baas-tauri backend update"
authors = ["Kiramei"]

[dependencies]
# Borrow from workspace
baas-term = { workspace = true }
serde = { workspace = true }
tauri = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
uuid = { workspace = true }
portable-pty = { workspace = true }
# Updater Specified Packages
git2 = { version = "0.21.0" }
zip = { version = "8.6.0" }
tar = { version = "0.4.44" }
toml = { version = "1.1.2" }
reqwest = { version = "0.13.4", features = ["json", "blocking", "stream"] }
flate2 = { version = "1.1.5" }
sha2 = { version = "0.11.0" }
