[package]
name = "baas-term"
version = "0.0.4"
edition = "2024"
readme = "README.md"
description = "Package used for baas-updater terminal display"
authors = ["Kiramei"]

[dependencies]
# Borrow from workspace
tauri = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
portable-pty = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
