import importlib.util
import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
MODULES = ROOT / "src-tauri/gen/android/app/src/main/python/android_backend"


def load(name):
    spec = importlib.util.spec_from_file_location(name, MODULES / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class NativeCaptureTest(unittest.TestCase):
    def test_native_preview_command_is_allowed(self):
        import tomllib
        permissions = tomllib.loads((ROOT / "src-tauri/permissions/autogenerated/commands/mobile-commands.toml").read_text())
        self.assertIn("android_game_native_preview", permissions["permission"][0]["commands"]["allow"])

    def test_native_selection_overrides_legacy_adb_and_is_idempotent(self):
        bootstrap = load("bootstrap")
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "service/conf").mkdir(parents=True)
            manager = root / "service/conf/manager.py"
            manager.write_text(
                "import os, copy\nclass Manager:\n"
                "    @staticmethod\n    def normalize(data):\n"
                "        normalized = copy.deepcopy(data)\n"
                "        normalized['control_method'] = 'adb'\n"
                "        normalized['screenshot_method'] = 'adb'\n"
                "        return normalized\n", encoding="utf-8")
            injection = root / "service/injection.py"
            injection.write_text(
                "import os\ndef _scrcpy_virtual_display_enabled() -> bool:\n    return True\n",
                encoding="utf-8")
            bootstrap._patch_android_native_capture_runtime(root)
            first = manager.read_text()
            bootstrap._patch_android_native_capture_runtime(root)
            self.assertEqual(first, manager.read_text())
            namespace = {}
            exec(first, namespace)
            with patch.dict(os.environ, {"BAAS_ANDROID_NATIVE_CAPTURE": "1"}):
                normalized = namespace["Manager"].normalize({"server": "JP", "custom": 7})
                self.assertEqual(normalized["screenshot_method"], "android_local")
                self.assertEqual(normalized["control_method"], "android_local")
                self.assertEqual(normalized["adbPort"], "7912")
                self.assertEqual(normalized["custom"], 7)
                exec(injection.read_text(), namespace)
                self.assertFalse(namespace["_scrcpy_virtual_display_enabled"]())
            self.assertIn("from android_backend.native_device import", (root / "service/android_local_device.py").read_text())

    def test_control_uses_local_rpc_and_preserves_duration(self):
        native = load("native_device")
        conn = type("Connection", (), {"serial": "127.0.0.1:7912"})()
        control = native.AndroidLocalControl(conn)
        with patch.object(native, "_rpc", return_value=True) as rpc:
            self.assertTrue(control.click(10, 20))
            rpc.assert_called_with("click", [10, 20])
            control.swipe(10, 20, 30, 40, 0.5)
            rpc.assert_called_with("swipe", [10, 20, 30, 40, 100])
            control.long_click(10, 20, 0.8)
            rpc.assert_called_with("swipe", [10, 20, 10, 20, 160])


if __name__ == "__main__":
    unittest.main()
