/* This file is generated by scripts/i18n.mjs. */
import "i18next";
import type { TranslationResource } from "./i18n";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: "translation";
    keySeparator: false;
    returnNull: false;
    resources: {
      translation: TranslationResource;
    };
  }
}
