use std::{
    panic::{self, AssertUnwindSafe},
    sync::{
        Arc, Mutex,
        atomic::{AtomicBool, Ordering},
        mpsc::Sender,
    },
    thread,
    time::Duration,
};

use crate::types::{RendererEvent, State, TaskCompletion, TaskHandle, TaskSpec};

pub fn create_thread_task(
    task_id: &str,
    region_id: &str,
    step_index: u8,
    name: &str,
    command: &str,
) -> TaskSpec {
    TaskSpec {
        task_id: task_id.to_string(),
        region_id: region_id.to_string(),
        step_index,
        step_total: 4,
        name: name.to_string(),
        command: command.to_string(),
        program: String::new(),
        args: Vec::new(),
    }
}

/// Spawns a thread task and forwards its output to the build renderer.
///
/// `spec` defines the dashboard task metadata, `args` is moved into the worker
/// function, and `job` receives `(output, cancellation_token, args)`. Returns
/// [`Ok(())`] after the worker thread is spawned, or an error if the session is
/// stale or the start event cannot be sent.
pub fn spawn_thread_task<F, A>(
    inner: &Arc<Mutex<State>>,
    session_id: &str,
    spec: TaskSpec,
    renderer_tx: &Sender<RendererEvent>,
    completion_tx: &Sender<TaskCompletion>,
    args: A,
    job: F,
) -> Result<(), String>
where
    F: FnOnce(ThreadOutput, Arc<AtomicBool>, A) -> Result<(), String> + Send + 'static,
    A: Send + 'static,
{
    {
        let state = inner.lock().map_err(|_| "build manager lock poisoned")?;
        if state.current_session_id.as_deref() != Some(session_id) {
            return Err("stale build session".to_string());
        }
    }

    let cancel = Arc::new(AtomicBool::new(false));
    let handle = Arc::new(TaskHandle::Thread {
        cancel: Arc::clone(&cancel),
    });

    {
        let mut state = inner.lock().map_err(|_| "build manager lock poisoned")?;
        state.tasks.insert(spec.task_id.clone(), handle);
    }

    renderer_tx
        .send(RendererEvent::TaskStarted(spec.clone()))
        .map_err(|error| error.to_string())?;

    let thread_inner = Arc::clone(inner);
    let thread_tx = renderer_tx.clone();
    let thread_completion_tx = completion_tx.clone();
    let thread_task_id = spec.task_id.clone();
    let thread_region_id = spec.region_id.clone();
    thread::spawn(move || {
        let output = ThreadOutput {
            task_id: thread_task_id.clone(),
            region_id: thread_region_id.clone(),
            tx: thread_tx.clone(),
        };
        let result =
            panic::catch_unwind(AssertUnwindSafe(|| job(output, Arc::clone(&cancel), args)))
                .unwrap_or_else(|_| Err("thread task panicked".to_string()));
        let cancelled = cancel.load(Ordering::Relaxed);

        if let Ok(mut state) = thread_inner.lock() {
            state.tasks.remove(&thread_task_id);
        }

        let (status, error) = if cancelled {
            ("stopped".to_string(), None)
        } else {
            match result {
                Ok(()) => ("success".to_string(), None),
                Err(error) => ("failed".to_string(), Some(error)),
            }
        };
        let success = status == "success";

        let _ = thread_tx.send(RendererEvent::TaskFinished {
            task_id: thread_task_id.clone(),
            region_id: thread_region_id,
            status,
            exit_code: None,
            error,
        });
        let _ = thread_completion_tx.send(TaskCompletion {
            task_id: thread_task_id,
            success,
        });
    });

    Ok(())
}

#[derive(Clone)]
pub struct ThreadOutput {
    pub task_id: String,
    pub region_id: String,
    pub tx: Sender<RendererEvent>,
}

impl ThreadOutput {
    /// Writes raw terminal text to the renderer for this thread task.
    ///
    /// `chunk` is the complete text chunk to append. It may contain CRLF,
    /// carriage returns, or ANSI control sequences generated by higher-level
    /// helpers. Returns nothing; send failures are intentionally ignored
    /// because they mean the build session was already closed.
    fn write(&self, chunk: &str) {
        self.write_bytes(chunk.as_bytes());
    }

    /// Writes raw terminal bytes to the renderer for this thread task.
    ///
    /// `chunk` is forwarded unchanged to the build renderer. Use this only for
    /// low-level integration points; prefer `log`, `spinner`, or `progress_bar`
    /// for normal thread UI output. Returns nothing; send failures are ignored.
    fn write_bytes(&self, chunk: &[u8]) {
        let _ = self.tx.send(RendererEvent::Output {
            task_id: self.task_id.clone(),
            region_id: self.region_id.clone(),
            chunk: chunk.to_vec(),
        });
    }

    /// Creates a structured log writer for this thread task.
    ///
    /// The returned `ThreadLog` writes normal lines and reusable repaint areas
    /// without exposing ANSI escape sequences to callers.
    fn log(&self) -> ThreadLog {
        ThreadLog {
            output: self.clone(),
        }
    }

    /// Creates a spinner renderer bound to this thread task.
    ///
    /// `label` is the stable text shown after the spinner frame. The returned
    /// `ThreadSpinner` owns its animation state and writes one repainting line.
    fn spinner(&self, label: impl Into<String>) -> ThreadSpinner {
        ThreadSpinner::new(self.clone(), label)
    }

    /// Creates a progress bar renderer bound to this thread task.
    ///
    /// `label` is the stable text shown before the bar, `total` is the maximum
    /// progress value, and `width` is the number of character cells in the bar.
    /// The returned `ThreadProgressBar` owns current progress and repaint state.
    fn progress_bar(
        &self,
        label: impl Into<String>,
        total: u64,
        width: usize,
    ) -> ThreadProgressBar {
        ThreadProgressBar::new(self.clone(), label, total, width)
    }

    /// Runs a closure while a spinner is animated in the background.
    ///
    /// `label` is the stable spinner label, `success_message` is rendered when
    /// the closure returns `Ok`, and `run` contains the long-running work. The
    /// closure receives a `ThreadSpinnerGuard` that can update transient detail
    /// text. Returns the closure result and always stops the spinner before
    /// returning.
    fn with_spinner<T, F>(
        &self,
        label: impl Into<String>,
        success_message: impl Into<String>,
        run: F,
    ) -> Result<T, String>
    where
        F: FnOnce(&ThreadSpinnerGuard) -> Result<T, String>,
    {
        let mut spinner = ThreadSpinnerGuard::start(self.clone(), label);
        let result = run(&spinner);

        match &result {
            Ok(_) => spinner.finish(ThreadLogStyle::Success, success_message.into()),
            Err(error) => spinner.finish(scope_error_style(error), error),
        }

        result
    }

    /// Runs a closure with a progress bar that is finalized automatically.
    ///
    /// `label`, `total`, and `width` configure the progress bar; `success_message`
    /// is rendered when the closure returns `Ok`. The closure receives a mutable
    /// `ThreadProgressBar` and should call `set` or `inc` as work advances.
    /// Returns the closure result and always finishes the progress line.
    fn with_progress_bar<T, F>(
        &self,
        label: impl Into<String>,
        total: u64,
        width: usize,
        success_message: impl Into<String>,
        run: F,
    ) -> Result<T, String>
    where
        F: FnOnce(&mut ThreadProgressBar) -> Result<T, String>,
    {
        let mut progress_bar = self.progress_bar(label, total, width);
        let result = run(&mut progress_bar);

        match &result {
            Ok(_) => progress_bar.finish(ThreadLogStyle::Success, success_message.into()),
            Err(error) => progress_bar.finish(scope_error_style(error), error),
        }

        result
    }
}

const ANSI_RESET: &str = "\x1b[0m";
const ANSI_CLEAR_LINE: &str = "\r\x1b[2K";
const SPINNER_FRAMES: [&str; 4] = ["-", "\\", "|", "/"];

#[derive(Clone, Copy)]
enum ThreadLogStyle {
    Plain,
    Info,
    Success,
    Warning,
    Error,
    Accent,
    Muted,
}

impl ThreadLogStyle {
    fn ansi_code(self) -> Option<&'static str> {
        match self {
            ThreadLogStyle::Plain => None,
            ThreadLogStyle::Info => Some("\x1b[36m"),
            ThreadLogStyle::Success => Some("\x1b[32m"),
            ThreadLogStyle::Warning => Some("\x1b[33m"),
            ThreadLogStyle::Error => Some("\x1b[31m"),
            ThreadLogStyle::Accent => Some("\x1b[35m"),
            ThreadLogStyle::Muted => Some("\x1b[90m"),
        }
    }
}

#[derive(Clone)]
struct ThreadLog {
    output: ThreadOutput,
}

impl ThreadLog {
    /// Writes a single styled log line and terminates it with CRLF.
    ///
    /// `style` controls the visual treatment of the line, and `message` is the
    /// text to render. Returns nothing.
    fn line(&self, style: ThreadLogStyle, message: impl AsRef<str>) {
        self.output
            .write(&format!("{}\r\n", style_text(style, message.as_ref())));
    }

    /// Writes multiple styled log lines and terminates each line with CRLF.
    ///
    /// `style` controls the visual treatment of every line, and `lines` is the
    /// ordered set of messages to render. Returns nothing.
    fn lines<'a>(&self, style: ThreadLogStyle, lines: impl IntoIterator<Item = &'a str>) {
        for line in lines {
            self.line(style, line);
        }
    }

    /// Creates a single-line repaint area.
    ///
    /// The returned `ThreadLineRepaint` rewrites one terminal line in place
    /// until `finish` is called.
    fn line_repaint(&self) -> ThreadLineRepaint {
        ThreadLineRepaint {
            output: self.output.clone(),
            rendered: false,
        }
    }

    /// Creates a multi-line repaint area.
    ///
    /// The returned `ThreadBlockRepaint` rewrites the same group of terminal
    /// lines in place and tracks how many lines were rendered previously.
    fn block_repaint(&self) -> ThreadBlockRepaint {
        ThreadBlockRepaint {
            output: self.output.clone(),
            rendered_lines: 0,
        }
    }
}

pub struct ThreadLineRepaint {
    output: ThreadOutput,
    rendered: bool,
}

impl ThreadLineRepaint {
    /// Repaints the current single-line area without adding a newline.
    ///
    /// `style` controls the visual treatment of the line, and `message` is the
    /// complete line content. Returns nothing.
    fn render(&mut self, style: ThreadLogStyle, message: impl AsRef<str>) {
        let prefix = if self.rendered { ANSI_CLEAR_LINE } else { "" };
        self.output
            .write(&format!("{prefix}{}", style_text(style, message.as_ref())));
        self.rendered = true;
    }

    /// Repaints the line one final time and moves the cursor to the next line.
    ///
    /// `style` controls the final visual treatment, and `message` is the final
    /// line content. Returns nothing.
    fn finish(&mut self, style: ThreadLogStyle, message: impl AsRef<str>) {
        self.render(style, message);
        self.output.write("\r\n");
        self.rendered = false;
    }
}

pub struct ThreadBlockRepaint {
    output: ThreadOutput,
    rendered_lines: usize,
}

impl ThreadBlockRepaint {
    /// Repaints a multi-line block in place.
    ///
    /// `style` controls the visual treatment of each line, and `lines` is the
    /// complete block content for this frame. Returns nothing.
    fn render<'a>(&mut self, style: ThreadLogStyle, lines: impl IntoIterator<Item = &'a str>) {
        self.rewind_previous_frame();

        let mut rendered_lines = 0;
        for line in lines {
            self.output
                .write(&format!("{}\r\n", style_text(style, line)));
            rendered_lines += 1;
        }

        self.rendered_lines = rendered_lines;
    }

    /// Leaves the current block visible and starts future output below it.
    ///
    /// This method intentionally preserves the last rendered block. It returns
    /// nothing and resets repaint bookkeeping.
    fn finish(&mut self) {
        self.rendered_lines = 0;
    }

    fn rewind_previous_frame(&self) {
        if self.rendered_lines == 0 {
            return;
        }

        self.output
            .write(&format!("\x1b[{}F\x1b[J", self.rendered_lines));
    }
}

pub struct ThreadSpinner {
    output: ThreadOutput,
    label: String,
    frame_index: usize,
    rendered: bool,
}

impl ThreadSpinner {
    /// Creates a spinner that renders into a single repainting terminal line.
    ///
    /// `output` is the target thread output sink, and `label` is the stable text
    /// shown beside the spinner frame. Returns a new `ThreadSpinner`.
    fn new(output: ThreadOutput, label: impl Into<String>) -> Self {
        Self {
            output,
            label: label.into(),
            frame_index: 0,
            rendered: false,
        }
    }

    /// Advances the spinner by one frame and repaints its line.
    ///
    /// `detail` is optional transient text shown after the label. Returns
    /// nothing.
    fn tick(&mut self, detail: impl AsRef<str>) {
        let frame = SPINNER_FRAMES[self.frame_index % SPINNER_FRAMES.len()];
        self.frame_index += 1;

        let detail = detail.as_ref();
        let detail = if detail.is_empty() {
            String::new()
        } else {
            format!(" {detail}")
        };
        let prefix = if self.rendered { ANSI_CLEAR_LINE } else { "" };

        self.output.write(&format!(
            "{prefix}{} {}{}",
            style_text(ThreadLogStyle::Info, frame),
            self.label,
            detail
        ));
        self.rendered = true;
    }

    /// Repaints the spinner one final time and moves to the next line.
    ///
    /// `style` controls the final status color, and `message` is the final line
    /// content. Returns nothing.
    #[allow(dead_code)]
    fn finish(&mut self, style: ThreadLogStyle, message: impl AsRef<str>) {
        let prefix = if self.rendered { ANSI_CLEAR_LINE } else { "" };
        self.output.write(&format!(
            "{prefix}{}\r\n",
            style_text(style, message.as_ref())
        ));
        self.rendered = false;
    }
}

pub struct ThreadSpinnerGuard {
    output: ThreadOutput,
    stop: Arc<AtomicBool>,
    detail: Arc<Mutex<String>>,
    worker: Option<thread::JoinHandle<()>>,
    finished: bool,
}

impl ThreadSpinnerGuard {
    /// Starts a background spinner for long-running scoped work.
    ///
    /// `output` is the target thread output sink, and `label` is the stable text
    /// shown beside the animated spinner. Returns a guard that stops the worker
    /// when `finish` or `drop` runs.
    fn start(output: ThreadOutput, label: impl Into<String>) -> Self {
        let label = label.into();
        let stop = Arc::new(AtomicBool::new(false));
        let detail = Arc::new(Mutex::new(String::new()));
        let worker_output = output.clone();
        let worker_stop = Arc::clone(&stop);
        let worker_detail = Arc::clone(&detail);

        let worker = thread::spawn(move || {
            let mut spinner = worker_output.spinner(label);
            while !worker_stop.load(Ordering::Relaxed) {
                let detail = worker_detail
                    .lock()
                    .map(|detail| detail.clone())
                    .unwrap_or_default();
                spinner.tick(detail);
                thread::sleep(Duration::from_millis(100));
            }
        });

        Self {
            output,
            stop,
            detail,
            worker: Some(worker),
            finished: false,
        }
    }

    /// Updates the transient text rendered beside the spinner.
    ///
    /// `detail` is replaced atomically for the background spinner loop. Returns
    /// nothing.
    fn set_detail(&self, detail: impl Into<String>) {
        if let Ok(mut current) = self.detail.lock() {
            *current = detail.into();
        }
    }

    /// Stops the spinner and renders a final status line.
    ///
    /// `style` controls the final status color, and `message` is the final line
    /// content. Returns nothing.
    fn finish(&mut self, style: ThreadLogStyle, message: impl AsRef<str>) {
        self.stop_worker();
        self.output.write(&format!(
            "{ANSI_CLEAR_LINE}{}\r\n",
            style_text(style, message.as_ref())
        ));
        self.finished = true;
    }

    fn stop_worker(&mut self) {
        self.stop.store(true, Ordering::Relaxed);
        if let Some(worker) = self.worker.take() {
            let _ = worker.join();
        }
    }
}

impl Drop for ThreadSpinnerGuard {
    fn drop(&mut self) {
        if self.finished {
            return;
        }

        self.stop_worker();
        self.output.write(&format!(
            "{ANSI_CLEAR_LINE}{}\r\n",
            style_text(ThreadLogStyle::Warning, "spinner interrupted")
        ));
        self.finished = true;
    }
}

pub struct ThreadProgressBar {
    output: ThreadOutput,
    label: String,
    total: u64,
    width: usize,
    current: u64,
    rendered: bool,
}

impl ThreadProgressBar {
    /// Creates a progress bar that renders into a single repainting line.
    ///
    /// `output` is the target thread output sink, `label` is shown before the
    /// bar, `total` is the completed value, and `width` is the visual bar width.
    /// Returns a new `ThreadProgressBar`.
    fn new(output: ThreadOutput, label: impl Into<String>, total: u64, width: usize) -> Self {
        Self {
            output,
            label: label.into(),
            total: total.max(1),
            width: width.max(1),
            current: 0,
            rendered: false,
        }
    }

    /// Sets the current progress value and repaints the bar.
    ///
    /// `current` is clamped to `total`, and `detail` is optional transient text
    /// shown after the percentage. Returns nothing.
    fn set(&mut self, current: u64, detail: impl AsRef<str>) {
        self.current = current.min(self.total);
        self.render(detail.as_ref());
    }

    /// Increments the current progress value and repaints the bar.
    ///
    /// `delta` is added to the previous value and clamped to `total`; `detail`
    /// is optional transient text shown after the percentage. Returns nothing.
    fn inc(&mut self, delta: u64, detail: impl AsRef<str>) {
        self.set(self.current.saturating_add(delta), detail);
    }

    /// Completes the progress bar and moves to the next line.
    ///
    /// `style` controls the final status color, and `message` is the final line
    /// content. Returns nothing.
    fn finish(&mut self, style: ThreadLogStyle, message: impl AsRef<str>) {
        self.current = self.total;
        let prefix = if self.rendered { ANSI_CLEAR_LINE } else { "" };
        self.output.write(&format!(
            "{prefix}{}\r\n",
            style_text(style, message.as_ref())
        ));
        self.rendered = false;
    }

    fn render(&mut self, detail: &str) {
        let filled =
            (((self.current as usize) * self.width) / (self.total as usize)).min(self.width);
        let percent = (self.current * 100) / self.total;
        let detail = if detail.is_empty() {
            String::new()
        } else {
            format!(" {}", style_text(ThreadLogStyle::Muted, detail))
        };
        let prefix = if self.rendered { ANSI_CLEAR_LINE } else { "" };
        let (done, todo) = progress_bar_segments(filled, self.width);

        self.output.write(&format!(
            "{prefix}{} {}  {} {}  {}/{}{}",
            style_text(ThreadLogStyle::Accent, &format!("{:<18}", self.label)),
            style_text(ThreadLogStyle::Info, &format!("{percent:>3}%")),
            style_text(ThreadLogStyle::Accent, &done),
            style_text(ThreadLogStyle::Muted, &todo),
            style_text(ThreadLogStyle::Info, &format!("{:>3}", self.current)),
            style_text(ThreadLogStyle::Muted, &self.total.to_string()),
            detail
        ));
        self.rendered = true;
    }
}

impl Drop for ThreadProgressBar {
    fn drop(&mut self) {
        if self.rendered {
            self.output.write(&format!(
                "{ANSI_CLEAR_LINE}{}\r\n",
                style_text(ThreadLogStyle::Warning, "progress interrupted")
            ));
            self.rendered = false;
        }
    }
}

fn progress_bar_segments(filled: usize, width: usize) -> (String, String) {
    ("━".repeat(filled), "─".repeat(width.saturating_sub(filled)))
}

fn style_text(style: ThreadLogStyle, text: &str) -> String {
    match style.ansi_code() {
        Some(code) => format!("{code}{text}{ANSI_RESET}"),
        None => text.to_string(),
    }
}

fn scope_error_style(error: &str) -> ThreadLogStyle {
    if error.to_ascii_lowercase().contains("cancel") {
        ThreadLogStyle::Warning
    } else {
        ThreadLogStyle::Error
    }
}
