name: Sync to CNB

on:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to CNB
        if: github.repository == 'Kiramei/baas-tauri'
        uses: ./.github/actions/sync-to-cnb
        with:
          target-url: https://cnb.cool/kiramei/baas-tauri.git
          password: ${{ secrets.CNB_SYNC_TOKEN }}
